name: Erlang CI
on: [push]
jobs:
  build:
    runs-on:
      group: SelfHostedDefault
      labels: ubuntu-22.04-small
    strategy:
      matrix:
        erlang: [26, '27']

    container:
      image: erlang:${{matrix.erlang}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      env:
        cache-name: rebar3
      with:
        path: |
          ~/.cache/rebar3
          _build
        key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
        restore-keys: |
          ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3
          ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}
    - name: Compile
      run: make
    - name: Checks
      run: make test
